### ISSUE TITLE
feature-ButtonAnimation

### ISSUE THREAD

**Issue by yerimee82** [MC3-Team16-Na3ver/watch-you#12]
## Description
⌚️ Watch 보내기 버튼 애니메이션 구현 입니다. 

## To-do
- [x] 누르기 전 기본 상태 SEND 버튼 구현하기
- [x] 눌렀을 때 spread 효과 애니메이션 구현하기 
- [ ] 일정 시간 꾹 눌러야 -> 전송 완료 되도록 + 전송 완료 화면 구현하기
- [ ] 보내고 난 후, 타이머 동작 구현하기
- [ ] 지난 시간 비례해서 버튼 차오르는 애니메이션 구현하기

<br>

## ETC
기타사항
