### ISSUE TITLE
feature-Login

### ISSUE THREAD

**Issue by Eric030406** [MC3-Team16-Na3ver/watch-you#16]
## Description
앱 소셜 로그인 기능 구현입니다.

## To-do

- [ ] 소셜 로그인 구현(애플, 카카오)

- [ ]  Firebase Firestore와 소셜 로그인 연동하기

## ETC
- [ ] uid를 통해서 계정 중복 생성 방지 로직 구현
