### ISSUE TITLE
Watch View 아키텍처 적용하여 UI와 데이터 처리하기 

### ISSUE THREAD

**Issue by yerimee82** [MC3-Team16-Na3ver/watch-you#51]
## Description
Watch View를 그릴 예정입니다. 
MVVM 아키텍처를 사용하여 뷰의 상태를 관리합니다. 

## To-do
- [x] 버튼 UI 구현하기
- [x] 꾹 눌렀을 때 프로그래스 바 구현하기
- [x] 게이지가 다 찼을 때 전송 시도를 하는 화면 구현하기(로띠로 로딩중 상태와 같이..)
- [x] 전송 성공 실패 화면 구현하기
- [x] 보내기 횟수 표현화면 구현하기(하트로 5개) + 시간 30분마다 하트 채워지도록 

## ETC
기타사항
