### ISSUE TITLE
feature- ios system 로직 구현

### ISSUE THREAD

**Issue by mun9769** [MC3-Team16-Na3ver/watch-you#58]
## Description
설명을 작성해주세요

## To-do
- [x] 알림창 띄우는 함수
- [x] 링크공유창 띄우는 함수
- [ ] 초대코드 유효한지 검사하는 함수

**Comment by mun9769** [comment]
초대코드 생성은 에릭이  #57 이슈에서 구현했습니다.
