### ISSUE TITLE
feature- 워치코드 합치기

### ISSUE THREAD

**Issue by mun9769** [MC3-Team16-Na3ver/watch-you#61]
## Description
워치코드 합치기

## To-do
* [x] 예리미 코드 동작 방식 이해하기
* [ ] watch에 lottie 적용하기
* [ ] 전송중, 전송완료, 전송실패 애니메이션 연결하기

**Comment by mun9769** [comment]
watch에서 lottie는 나중 스프린트에 넣고싶습니다. 
지금은 전송 후 response를 받았을 때 성공화면 혹은 실패화면으로 넘어가도록 하였습니다.
