### ISSUE TITLE
GCF DB CRUD 구현하기 

### ISSUE THREAD

**Issue by yerimee82** [MC3-Team16-Na3ver/watch-you#79]
## Description
Firestore에 DB 접근을 클라이언트단에서 진행하는 것을 
Cloud Functions을 활용하여 변경하여 구현합니다. 

## To-do
- [ ] CGF DB CRUD 구현하기
- [ ] Firebase 프로젝트 연결하기
- [ ] 클라이언트에서 호출하여 정상적으로 동작되는 지 확인하기 

## ETC
기타사항
